# ─── dovecot.conf — Configuración principal de Dovecot ────────────────────
# 4nexa Mailgun — Mail Node

# Protocolos habilitados
protocols = imap lmtp

# Incluir configuraciones adicionales
!include conf.d/*.conf
