# ─── 20-imap.conf — Configuración IMAP ───────────────────────────────────
# 4nexa Mailgun — Mail Node

protocol imap {
  mail_plugins = $mail_plugins quota imap_quota

  # Límite de conexiones simultáneas por usuario
  mail_max_userip_connections = 20

  # Límite de conexiones totales
  # service imap-login ajustado abajo
}

service imap-login {
  inet_listener imap {
    port = 143
    address = *
  }
  inet_listener imaps {
    port = 993
    ssl = yes
    address = *
  }
}

service imap {
  # Un proceso por conexión (más seguro, menor rendimiento bajo alta carga)
  service_count = 1
}
