# ─── 20-lmtp.conf — LMTP para entrega desde Postfix ─────────────────────
# 4nexa Mailgun — Mail Node
# Postfix entrega via LMTP TCP a dovecot:24

protocol lmtp {
  mail_plugins = $mail_plugins sieve quota
  postmaster_address = postmaster@localhost
}

service lmtp {
  # Listener TCP para integración con Postfix en Docker
  inet_listener lmtp {
    port = 24
    address = *
  }
}
